Campground.insertMany([
    {title: 'Elk Cliffs', location: 'North Richland Hills, Texas'},
    {title: 'Mountain View Retreat', location: 'Aspen, Colorado'},
    {title: 'Sunset Shores', location: 'Santa Barbara, California'},
    {title: 'Pine Forest Escape', location: 'Flagstaff, Arizona'},
    {title: 'Lakeside Haven', location: 'Lake George, New York'},
    {title: 'Desert Oasis', location: 'Palm Springs, California'},
    {title: 'Canyon Bluff', location: 'Sedona, Arizona'},
    {title: 'Whispering Pines', location: 'Lake Tahoe, Nevada'},
    {title: 'Seaside Serenity', location: 'Myrtle Beach, South Carolina'},
    {title: 'Hilltop Hideaway', location: 'Boulder, Colorado'},
    {title: 'Forest Glade', location: 'Portland, Oregon'},
    {title: 'Valley Vista', location: 'Jackson Hole, Wyoming'},
    {title: 'Wildflower Meadow', location: 'Madison, Wisconsin'},
    {title: 'Rustic River Retreat', location: 'Bend, Oregon'},
    {title: 'Starry Night Camp', location: 'Moab, Utah'},
    {title: 'Golden Sands', location: 'Destin, Florida'},
    {title: 'Mystic Mountain', location: 'Gatlinburg, Tennessee'},
    {title: 'Tranquil Trails', location: 'Burlington, Vermont'},
    {title: 'Eagle’s Nest', location: 'Anchorage, Alaska'},
    {title: 'Crystal Lake Camp', location: 'Mammoth Lakes, California'},
    {title: 'Redwood Retreat', location: 'Eureka, California'},
    {title: 'Prairie Oasis', location: 'Sioux Falls, South Dakota'},
    {title: 'Hidden Creek', location: 'Boise, Idaho'},
    {title: 'Highland Haven', location: 'Asheville, North Carolina'},
    {title: 'Sandy Beach Escape', location: 'Pensacola, Florida'},
    {title: 'Misty Mountain', location: 'Bellingham, Washington'},
    {title: 'Sunny Grove', location: 'Gainesville, Florida'},
    {title: 'Cedar Cove', location: 'Reno, Nevada'},
    {title: 'Autumn Woods', location: 'Manchester, Vermont'},
    {title: 'Rocky Ridge', location: 'Durango, Colorado'},
    {title: 'Blue Horizon', location: 'Port Angeles, Washington'},
    {title: 'Serene Springs', location: 'Hot Springs, Arkansas'},
    {title: 'Golden Ridge', location: 'Rapid City, South Dakota'},
    {title: 'Pine Valley', location: 'Bozeman, Montana'},
    {title: 'Silver Lake', location: 'Dover, Delaware'},
    {title: 'Orchard Grove', location: 'Winchester, Virginia'},
    {title: 'Cypress Hollow', location: 'Houma, Louisiana'},
    {title: 'Eagle Rock', location: 'Cody, Wyoming'},
    {title: 'Bear Creek', location: 'Columbus, Ohio'}
    
])
.then(data=>{
    console.log('It Workerd')
})